#index:
#    path: /
#    controller: App\Controller\DefaultController::index

frontend:
    path:     /{path}
    controller: App\Controller\FrontendController::index
    requirements:
        path: .*
