
parameters:

    server_stream:
        reference_file: '%kernel.project_dir%/var/server_stream.json'
        config:
            server_port: 8888
            input_device: '/dev/video0'
            decoder:
                width: 640
                height: 480
                framerate: 30
                rescale_ts: false
            encoder:
                demuxer: 'mpegts'
                codec: 'mpeg1video'
                width: 640
                height: 480
                framerate: 30
                bitrate: 1000000
                bframes: 0
                rescale_ts: true
