
parameters:
    server_stream:
        sudo_bin: '/usr/bin/sudo'
        service_bin: '/usr/sbin/service'
        ffmpeg:
            service: 'ffmpegd'
            pid_file: '/var/run/ffmpeg-daemon.pid'
            log_file: '/var/log/ffmpeg-daemon.log'
        server_stream:
            service: 'serverstreamd'
            pid_file: '/var/run/serverstream-daemon.pid'
            log_file: '/var/log/serverstream-daemon.log'
            status_file: '%kernel.project_dir%/var/server_stream.json'
